name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check formatting
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '16'
          check-path: '.'

  build-test:
    name: ${{ matrix.os }} / ${{ matrix.build_type }}
    needs: [format]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure CMake
        run: >
          cmake -S . -B build
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DMINFI_BUILD_TESTS=ON
          -DMINFI_BUILD_BENCHMARKS=OFF

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} -j

      - name: Run tests
        run: ctest --test-dir build --output-on-failure --build-config ${{ matrix.build_type }}
